 use std::path::Path;

use crate::sandbox::docker::{DockerSandbox, SandboxResult};

#[derive(Debug)]
pub struct VerificationResult {
    pub passed: bool,
    pub command: String,
    pub exit_code: Option<i32>,
    pub stdout: String,
    pub stderr: String,
}

pub struct VerificationRunner {
    sandbox: DockerSandbox,
}

impl VerificationRunner {
    pub fn new() -> Self {
        Self {
            sandbox: DockerSandbox::new(),
        }
    }

    pub async fn verify(
        &self,
        workspace_path: &Path,
        command: &str,
    ) -> Result<VerificationResult, String> {
        println!("========================================");
        println!("VERIFICATION RUNNER");
        println!("Workspace: {}", workspace_path.display());
        println!("Verification command: {}", command);

        // The entire AI Coding Agent project is mounted into Docker as:
        //
        // F:\AI CODING AGENT
        //          ↓
        //     /workspace
        //
        // Verification commands generated by Gemini use paths relative
        // to the workspace root.
        //
        // Example:
        //
        //     cat backend/agent_test.txt
        //
        // must resolve inside Docker as:
        //
        //     /workspace/backend/agent_test.txt
        //
        // Therefore verification MUST run from /workspace.
        let result: SandboxResult = self
            .sandbox
            .run_in_directory(workspace_path, "/workspace", command)
            .await?;

        let verification = VerificationResult {
            passed: result.success,
            command: command.to_string(),
            exit_code: result.exit_code,
            stdout: result.stdout,
            stderr: result.stderr,
        };

        if verification.passed {
            println!("VERIFICATION RESULT: PASS");
        } else {
            println!("VERIFICATION RESULT: FAIL");
        }

        println!("Exit code: {:?}", verification.exit_code);

        if !verification.stdout.is_empty() {
            println!("STDOUT:");
            println!("{}", verification.stdout);
        }

        if !verification.stderr.is_empty() {
            println!("STDERR:");
            println!("{}", verification.stderr);
        }

        println!("========================================");

        Ok(verification)
    }
}